sudo: required
services:
    - docker
before-install:
    - docker build -t lokialice/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lokialice/docker-react npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-086203154370"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"